### ISSUE TITLE
Implement two essential operations

### ISSUE THREAD

**Issue by irnc** [grodno-city/alis-web-request#2]
- `sendInitialQuery({ year: 2016 })`
  - which should send query and initialize session on library-side
- `getPage(pageUrl)`
  - which will reuse session initiated by `sendInitialQuery` and get page from library based on it

This is not a detailed API, just an essential parts. Operations could operate using callbacks or Promises. Somehow they should get base URL of a library system.

**Comment by DemyanchikVadim** [comment]
Implemented operation **sendInitialQuery**
jar stored inside function, we want to reuse him in other requests. 
```
function sendInitialQuery(query, callback) {
  if (!query.year) {
    return process.nextTick(callback, new Error('query.year is not provided'));
  }
  const j = request.jar();
  const INITIAL_URL = `${query.alisEndpoint}/alis/EK/do_searh.php?radiodate=simple&valueINP=${query.year}&tema=1&tag=6`;
  request({ url: INITIAL_URL, jar: j }, (err, response, body) => {
    if (err) {
      callback(err);
      return;
    }
    callback(null, { page: body, jar: j });
  });
}
```

Implemented operation **sendInitialQuery**
```
getPage(options, callback) {
  request({ url: options.url, jar: options.jar }, (err, response, body) => {
    if (err) {
      return callback(err);
    }
    callback(null, body);
  });
}
```
